sudo: false
language: node_js
node_js: stable
notifications:
  email: false
before_script:
  - npm prune
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm install
script:
  - sk-bundle
  - if [ "${TRAVIS_SECURE_ENV_VARS}" = "true" ]; then
    npm test -- --all;
    else
    npm test -- --browsers Firefox;
    fi
after_success:
  - sk-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
env:
  global:
    - secure: k00BVlgfFnvYE/wikDY9c8HhPR/hgeB1U9cIs8rV3SNGVau1VtYsvYLAiLatO7VqE6HmITr5VxQMoOgkAeO/ATS7tXIJydlq0GMTwjtx38Vtc3/HqfuXKVVpZBahIHyNraodiGs5gl0aHZUH8pExNJl3i19aOHZXIXj6NUXNlOA=
    - secure: bbZWoSRo2838rWq/BdqUi3pMD4aXt6VdpRwNgC80GyxqS44pRvexV45bax4jfH+Cvv/IoDjQFrFalMEcDkhxfQ37EwMJB0YW1tfiUwqRZGHyKjKXoUBzOznNObxTVp7tEjra+MFKVsUKsKE80XFFgaKV6CvNbMr+qYxql+EP70M=
